apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carts
  labels:
    k8s-app: carts
  namespace: sock-shop
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: carts
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
