apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue-db
  labels:
    k8s-app: catalogue-db
  namespace: sock-shop
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: catalogue-db
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: mysql
    interval: 1s
