apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  labels:
    k8s-app: rabbitmq
  namespace: sock-shop
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: rabbitmq
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: exporter
    interval: 1s
